"""
Library ingestion pipeline: converts PDF/DOCX/PPTX files in library/ to Markdown
and indexes them in knowledge/library-converted/ for agent reference.

Usage:
    python3 scripts/library-ingest.py
    python3 scripts/library-ingest.py --library-dir library/ --knowledge-dir knowledge/

Dependencies:
    pip install 'markitdown[pdf,docx]'
"""
from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

SUPPORTED_EXTENSIONS = {".pdf", ".docx", ".pptx", ".xlsx"}
CONVERTED_SUBDIR = "library-converted"


def _ensure_markitdown():
    """Import markitdown or exit with install instructions."""
    try:
        from markitdown import MarkItDown
        return MarkItDown()
    except ImportError:
        print(
            "ERROR: markitdown is not installed.\n"
            "Run:  pip install 'markitdown[pdf,docx]'\n"
            "Or with venv:  source .venv/bin/activate && pip install 'markitdown[pdf,docx]'",
            file=sys.stderr,
        )
        sys.exit(1)


def _extract_title(md_text: str, fallback: str) -> str:
    """Extract title from first Markdown heading, or use filename as fallback."""
    for line in md_text.splitlines():
        stripped = line.strip()
        if stripped.startswith("# "):
            return stripped.lstrip("# ").strip()
    return fallback


def _convert_file(md_converter, src: Path, dst: Path) -> dict:
    """Convert a single file and return metadata."""
    dst.parent.mkdir(parents=True, exist_ok=True)

    result = md_converter.convert(str(src))
    text = result.text_content or ""

    if len(text.strip()) < 50:
        return {
            "source": str(src),
            "status": "failed",
            "reason": "extracted text too short (< 50 chars)",
        }

    dst.write_text(text, encoding="utf-8")

    return {
        "source": str(src),
        "destination": str(dst),
        "title": _extract_title(text, src.stem),
        "file_type": src.suffix.lstrip("."),
        "word_count": len(text.split()),
        "converted_at": datetime.now(timezone.utc).isoformat(),
        "status": "ok",
    }


def _update_index(index_path: Path, entries: list[dict]) -> None:
    """Update library/_index.md with converted file entries."""
    ok_entries = [e for e in entries if e["status"] == "ok"]
    if not ok_entries:
        return

    header = "# Library Index\n\n"
    header += "Auto-generated by `scripts/library-ingest.py`. Do not edit manually.\n\n"
    header += "| Title | Type | Source | Converted | Words |\n"
    header += "|:------|:-----|:-------|:----------|------:|\n"

    existing_rows: dict[str, str] = {}
    if index_path.exists():
        for line in index_path.read_text(encoding="utf-8").splitlines():
            if line.startswith("|") and not line.startswith("| Title") and not line.startswith("|:"):
                parts = [p.strip() for p in line.split("|")]
                if len(parts) >= 5:
                    existing_rows[parts[3]] = line

    for entry in ok_entries:
        row = f"| {entry['title']} | {entry['file_type']} | `{entry['source']}` | {entry['converted_at'][:10]} | {entry['word_count']} |"
        existing_rows[f"`{entry['source']}`"] = row

    rows = "\n".join(existing_rows.values())
    index_path.write_text(f"{header}{rows}\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description="Convert library/ files to Markdown")
    parser.add_argument(
        "--library-dir",
        type=Path,
        default=Path("library"),
        help="Path to library directory (default: library/)",
    )
    parser.add_argument(
        "--knowledge-dir",
        type=Path,
        default=Path("knowledge"),
        help="Path to knowledge directory (default: knowledge/)",
    )
    args = parser.parse_args()

    library_dir: Path = args.library_dir
    knowledge_dir: Path = args.knowledge_dir

    if not library_dir.exists():
        print(f"library/ directory not found at {library_dir}. Nothing to ingest.")
        sys.exit(0)

    md_converter = _ensure_markitdown()
    output_dir = knowledge_dir / CONVERTED_SUBDIR
    output_dir.mkdir(parents=True, exist_ok=True)

    source_files = [
        f for f in library_dir.rglob("*") if f.suffix.lower() in SUPPORTED_EXTENSIONS
    ]

    if not source_files:
        print("No PDF/DOCX/PPTX/XLSX files found in library/.")
        sys.exit(0)

    print(f"Found {len(source_files)} file(s) to process.")

    results = []
    for src in sorted(source_files):
        rel = src.relative_to(library_dir)
        dst = output_dir / rel.with_suffix(".md")

        # Skip if already converted and source hasn't changed
        if dst.exists() and dst.stat().st_mtime >= src.stat().st_mtime:
            print(f"  SKIP (unchanged): {rel}")
            continue

        print(f"  CONVERT: {rel} ... ", end="", flush=True)
        try:
            entry = _convert_file(md_converter, src, dst)
            results.append(entry)
            print(entry["status"])
        except Exception as e:
            error_entry = {
                "source": str(src),
                "status": "failed",
                "reason": str(e),
            }
            results.append(error_entry)
            print(f"FAILED: {e}")

    # Update index
    index_path = library_dir / "_index.md"
    _update_index(index_path, results)

    # Summary
    ok_count = sum(1 for r in results if r["status"] == "ok")
    fail_count = sum(1 for r in results if r["status"] == "failed")
    print(f"\nDone: {ok_count} converted, {fail_count} failed.")
    print(json.dumps({"results": results}, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
